@url = http://localhost:3000

### Get request for redirection
GET {{url}}/myApp/api/HLKnRY

### Get request for redirection
GET {{url}}/myApp/api/

### Post request to generate a new shortCode
POST {{url}}/myApp/api
Content-Type: application/json

{
    "url": "https://github.com/aliveAndYoung"
}